### ISSUE TITLE
How to properly extend uiswitch styles?

### ISSUE THREAD

**Issue by monecchi** [fnky/uiswitch2#1]
Hi there. Thanks a lot for this awesome checkbox styles, UISwitch II really rocks! Although I'm already using it out of the box on my site project, I've been having a hard time on trying to extend uiswitch with my own styles.

It happens I'm quite new with Sass and I'm reading its documentation right now... I've managed how to set up Ruby and install Sass on my VPS server and also how to have sass watch the _uiswitch.scss file for any changes and then compile it. However, I'm not sure how to create new uiswitch variations with custom styles such as size or colors...

Here's what I've been trying to do:

I've created a new .scss file named uiswitch_custom.scss in the same directory as the default _uiswitch.scss file with the following content:

```
// UISwitch2
// A customizable UISwitch in pure CSS3.
// @author Christian Petersen <chrs@cbp.io>

@import 'uiswitch';

$uiswitch-active-tint: #3FA635;

.uiswitch-small {
@extend ui-switch($size: 35px, $on-tint: hotpink);
}
```

I've set up Sass to watch for any changes regarding .scss files within the /css directory I'm working on, but only the _uiswitch.scss is been compiled. On terminal I getting an error output stating the file uiswitch_custom.scss was watched, compiled but then deleted.

I've also tried to "extend" uiswitch as per your instructions by placing the following inside the _uiswitch.scss file, but then I got a compilation error:

```
.my-switch {
@extend %uiswitch;
border-radius: 4px;

// Background
&::before { border-radius: 2px; }

// Thumb
&::after { border-radius: 1px; }

// Checked background
&:checked { background: hotpink; }

// Checked thumb
&:checked::after { background-color: #333; }
}
```

 Could you please guide me in details on how to extend/create my own uiswitch styles?

Thanks a lot in advance.

Adriano Monecchi

**Comment by fnky** [comment]
In Sass, files starting with `_` (underscore) will get compiled as long as they're `@import`ed from other files that would essentially compile into a `.css` file.

You're doing the right thing in making your changes in your own file rather than changing the source file for `uiswitch`—so it can be updated without breaking your changes.

Can you post the error you get?

**Comment by monecchi** [comment]
Thanks for your quick reply.

Below is what I get on Mac Terminal every time I update my own file _uiswitch_custom.scss - It doen't happen if I update _uiswitch.scss though...

```
>>> New template detected: css/_uiswitch_custom.scss
>>> Deleted template detected: css/_uiswitch_custom.scss
>>> Deleted template detected: css/_uiswitch_custom_safe_save_163333.scss
>>> New template detected: css/_uiswitch_custom_safe_save_173843.scss
>>> Change detected to: css/_uiswitch_custom.scss
>>> Deleted template detected: css/_uiswitch_custom_safe_save_173843.scss
```

It seems to me there's something wrong with the content of the file _uiswitch_custom.scss which is simply the following:

```
// UISwitch2
// A customizable UISwitch in pure CSS3.
// @author Christian Petersen <chrs@cbp.io>

@import 'uiswitch';
$uiswitch-active-tint: #3FA635;

.uiswitch-small {
@extend ui-switch($size: 35px, $on-tint: hotpink);
}
```

As I've seen in Sass documentation I tried to use both <code>@import 'uiswitch';</code> and <code>@import "uiswitch";</code> I mean, with <code>'</code> or <code>"</code> but it doesn't result on a successful compilation...

**Comment by monecchi** [comment]
Hi there. I've managed on my own to solve the issue. It seems I had copied/pasted the usage example from your pen on Codepen website http://codepen.io/cbp/pen/qEQRww/ and it was causing the issue because the example showed the following:

```
.my-switch {
@extend ui-switch($size: 50px, $on-tint: hotpink);
}
```

So I was declaring **@ extend ui-switch** instead of **@ extend %uiswitch**

```
.my-switch {
@extend %uiswitch($size: 50px, $on-tint: hotpink);
}
```

By correcting it the file was properly compiled.

Regards,
Adriano Monecchi

**Comment by fnky** [comment]
Glad you got it working :-) However, it's strange to me that you didn't get the error reason printed out.
